ARG ERPNEXT_VERSION
FROM frappe/erpnext-worker:${ERPNEXT_VERSION}

USER root
COPY install_apps.sh /home/frappe/frappe-bench/
COPY apps.json /home/frappe/frappe-bench/
RUN /home/frappe/frappe-bench/install_apps.sh

USER frappe
